### PR TITLE
Initial netstandard2.0 port

### PR DESCRIPTION
**Pull request by bijakatlykkex**
Only NBitcoin.Indexer ported. Previous target should be untouched, just added extra code to places which was required for .Net Standard. Now it compiles for .Net Standard.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Awesome, but please, remove the legacy code. (non-async versions)
I should be able to run the tests, if it still passes I will then merge.

**Comment by NicolasDorier** [comment]
`ServicePointManager` exists in .net standard normally.
You should not fake that, or you will have very slow sync process.

**Comment by NicolasDorier** [comment]
You should use Microsoft.Extensions.Configuration, let's make it really .NET Standard.

**Comment by bijakatlykkex** [comment]
Thanks for reviewing the code:

About removing non-async code:
In many places I have modified the code like following:
```
#if WIN
                    table.ExecuteBatch(batch);
#else
                    table.ExecuteBatchAsync(batch).Wait();
#endif
```
Does it mean 
1- To change everything to async/await which will be lot of changes in many places not related to .Net Standard or
2- To change the above block to:
```
table.ExecuteBatchAsync(batch).Wait();
```

**Comment by bijakatlykkex** [comment]
About configuration:

Does it mean to change configuration for legacy .Net also to Microsoft.Extensions.Configuration and totally remove references to System.Configuration?

**Comment by NicolasDorier** [comment]
keep it simple now.
Do not use `table.ExecuteBatchAsync(batch).Wait();` but `table.ExecuteBatchAsync(batch).GetAwaiter().GetResult();` as it does not hide the real exception.

Yes remove dependency to System.Configuration

**Comment by NicolasDorier** [comment]
Ok so I managed to move QBitNinja to the new, cleaner csproj from Visual Studio 2017.
I plan to move to .NETCore in a second time.

I think it might help to use the same way for NBitcoin.Indexer: first moving to new csproj, then to .NETCore.

**Comment by NicolasDorier** [comment]
Can you squash your commits ? I think this PR is good first step.

**Comment by bijakatlykkex** [comment]
Squash done. System.Configuration removal is also on my schedule by default.

**Comment by NicolasDorier** [comment]
Can you fix the useless formatting in IndexerClient ? also keep out the change of csproj and configuration ? I think it is best to do this part in another pr.

**Comment by bijakatlykkex** [comment]
- IndexerClient formatting, many changes removed.
- csproj and configuration changes returned to original version.

For the options framework, I think https://github.com/aspnet/Options is being referenced. Please correct me if it is not correct. Thanks.

**Comment by NicolasDorier** [comment]
Ok I will test this PR and merge. Yes the option framework is this one.
I will migrate to new csproj after merging this PR, then we can start swapping to .netstandard.

**Comment by NicolasDorier** [comment]
I just migrated to new csproj style, everything is way cleaner now.
I bump version + update NBitcoin and QBitNinja to use this version.

**Comment by bijakatlykkex** [comment]
Thanks.
What is the plan for Indexer.Console? Will be completely omitted?

**Comment by NicolasDorier** [comment]
I remove Indexer.Console, because QBitNinja.Listener.Console should be used for indexing.

**Comment by NicolasDorier** [comment]
@bijakatlykkex there is basically two dependencies which are painful: ConfigurationManager and TraceSource, as you may know. On QBit, it is migrating to ASP.NET Core. Might take me a day of work.

**Comment by bijakatlykkex** [comment]
Thank you very much for adding .Net Core support.

About the console application, there was some options in indexer console, which I am not sure how they are satisfied in QBitNinja console. For example there was --From and --To options, also options to control what is being indexed like blocks, transactions, etc. This provided more control over the long indexing process (for example limiting the interval in which a crash happened few times, or running several processes in parallel specifically for balances). 

The QBitNinja console options seems to be much more limited in this regard.

**Comment by NicolasDorier** [comment]
QBitNinja console app should support the same thing, this was initially a copy paste of NBitcoin.Indexer. If that is not the case, then we should add that to QBitNinja console.

I just managed to pass NBitcoin.Indexer in netstandard2.0 without warning, right now running the tests.
If you want to run tests, you will have to use the new UserSecrets way of doing of .net core.

**Comment by NicolasDorier** [comment]
OK! I passed everything to netstandard2.0 :)

**Comment by bijakatlykkex** [comment]
Thank you for netstandard2.0 port!

As I checked Indexer console options seems not to be present in QBitNinja console.

**Comment by NicolasDorier** [comment]
@bijakatlykkex migrating QBitNinja to .NET Core is a huge pain because of breaking change in the Service Bus library of Microsoft. This led me to decide to drop dependency of Service bus, and rely only on Azure Storage, will combinaison of polling/leasing blocks. (https://github.com/Azure/azure-service-bus-dotnet/issues/65)

This will take more time. I will probably have to remove features from QBitNinja like HD wallet management, HTTP callbacks. Are you using those by any chance ?

**Comment by bijakatlykkex** [comment]
Thank you for your time and attention.

We do not use HD wallet management of QBitNinja, nor HTTP callbacks.

**Comment by NicolasDorier** [comment]
Last question, would it be a problem for you to use have RPC connection between the Indexer and Bitcoin Core? (not QBitNinja frontend)

**Comment by bijakatlykkex** [comment]
Actually we have some experience of connecting indexer to a node hosted in another machine, I do not see any specific problem for changing the internal connection method to RPC, except possible performance issue (https://bitcoin.stackexchange.com/questions/10197/bitcoind-json-rpc-requests-per-second).

**Comment by NicolasDorier** [comment]
Ok, the way I do that is by using IIS as a reverse proxy to RPC and configuring Let's encrypt on it.
This is just painful to setup, but work well.

**Comment by bijakatlykkex** [comment]
I am not sure I can understand what is described correctly, but I think new changes should not depend solely on IIS (for example they should also work on Kestrel)  to be platform independent as much as possible.

**Comment by NicolasDorier** [comment]
The connection between the indexer and RPC need either to be on the same machine or on another machine remotely.

RPC is not HTTPS by default, so you need to use a reverse proxy if you want to secure your communication.

**Comment by bijakatlykkex** [comment]
Thanks, it is much clear now; and as far as I understand this is Bitcoin Core side thing and it could be applied to all platforms. But I think at first, it is more important to implement the concept as it has been described above, then apply it to other platforms to take complete benefit of .Net Core port.

**Pull request merged**
